version: '3.8'

services:
  voicebot:
    build: .
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./.streamlit:/app/.streamlit
    restart: unless-stopped
