# Streamlit Secrets Configuration
# Actual API keys from your original implementation

# Azure Speech Services Configuration
AZURE_SPEECH_KEY = "2V4mGxPgCbSLiCSksJ56nlgiEywgYXjpsj6EYuRxJPLUoEwn3SFvJQQJ99BHACYeBjFXJ3w3AAAYACOGOEbu"
AZURE_SPEECH_REGION = "eastus"

# Azure OpenAI Configuration  
OPENAI_ENDPOINT = "https://admin-mezpjjio-eastus2.cognitiveservices.azure.com/openai/deployments/gpt-5-chat/chat/completions?api-version=2025-01-01-preview"
OPENAI_API_KEY = "18FLyH6d4f3WGhjz1HXtdUwOi6rZCWXxLVQH1LRtA98z8Zyhx4KrJQQJ99BHACHYHv6XJ3w3AAAAACOGQn6w"
